import createClient, { type Client } from "openapi-fetch"
import { getBaseUrl } from "@/lib/base-url"
import type { components, operations, paths } from "@/types/api.gen"

// Convenience aliases onto the generated schema (web/src/types/api.gen.ts, committed,
// regenerated by `bun run generate:api` from internal/web/swagger/openapi.yaml). These are
// derived references into the generated types, not hand-mirrored copies — never add a
// type here whose shape is retyped by hand instead of indexed from `components`/
// `operations`.
export type Instance = components["schemas"]["Instance"]
export type Setting = components["schemas"]["Setting"]
export type InstanceDetail = components["schemas"]["InstanceDetail"]
// A definitions-list row: a summary, plus the failure fields set on a definition
// that could not be loaded (see /api/definitions).
export type DefinitionEntry = components["schemas"]["DefinitionEntry"]
export type SettingField = components["schemas"]["SettingField"]
export type DefinitionDetail = components["schemas"]["DefinitionDetail"]
export type AddIndexer = components["schemas"]["AddIndexer"]
export type UpdateIndexer = components["schemas"]["UpdateIndexer"]
export type Capabilities = components["schemas"]["Capabilities"]
export type SearchMember = components["schemas"]["SearchMember"]
export type Release = components["schemas"]["Release"]
export type TestResult = components["schemas"]["TestResult"]
export type App = components["schemas"]["App"]
export type UpdateApp = components["schemas"]["UpdateApp"]
export type AppConnection = components["schemas"]["AppConnection"]
export type CreateConnection = components["schemas"]["CreateConnection"]
export type UpdateConnection = components["schemas"]["UpdateConnection"]
export type AnnounceConnection = components["schemas"]["AnnounceConnection"]
export type CreateAnnounceConnection = components["schemas"]["CreateAnnounceConnection"]
export type UpdateAnnounceConnection = components["schemas"]["UpdateAnnounceConnection"]
export type Notification = components["schemas"]["Notification"]
export type CreateNotification = components["schemas"]["CreateNotification"]
export type UpdateNotification = components["schemas"]["UpdateNotification"]
export type Proxy = components["schemas"]["Proxy"]
export type CreateProxy = components["schemas"]["CreateProxy"]
export type UpdateProxy = components["schemas"]["UpdateProxy"]
export type Solver = components["schemas"]["Solver"]
export type CreateSolver = components["schemas"]["CreateSolver"]
export type UpdateSolver = components["schemas"]["UpdateSolver"]
export type DownloadClient = components["schemas"]["DownloadClient"]
export type CreateDownloadClient = components["schemas"]["CreateDownloadClient"]
export type UpdateDownloadClient = components["schemas"]["UpdateDownloadClient"]
export type DownloadClientSettings = components["schemas"]["DownloadClientSettings"]
export type SyncProfile = components["schemas"]["SyncProfile"]
export type CreateSyncProfile = components["schemas"]["CreateSyncProfile"]
export type UpdateSyncProfile = components["schemas"]["UpdateSyncProfile"]
export type SyncReport = components["schemas"]["SyncReport"]
export type ConnectionSyncResult = components["schemas"]["ConnectionSyncResult"]
export type MintedApiKey = components["schemas"]["MintedApiKey"]
export type IndexerStats = components["schemas"]["IndexerStats"]
export type IndexerFailureCounts = components["schemas"]["IndexerStats"]["failures"]
export type IndexerBudget = components["schemas"]["IndexerBudget"]
export type IndexerBudgetKind = components["schemas"]["IndexerBudgetKind"]
export type CacheStats = components["schemas"]["CacheStats"]
export type DiagnosticCapture = components["schemas"]["DiagnosticCapture"]
export type CacheConfig = components["schemas"]["CacheConfig"]
export type CacheConfigUpdate = components["schemas"]["CacheConfigUpdate"]
export type ConnectionKind = components["schemas"]["AppConnection"]["kind"]
export type AnnounceKind = components["schemas"]["AnnounceConnection"]["kind"]
export type ProxyType = components["schemas"]["Proxy"]["type"]
export type DownloadClientKind = components["schemas"]["DownloadClient"]["kind"]
// LogLevel is the bare string union call sites switch on; components["schemas"]["LogLevel"]
// is the {level: LogLevel} wrapper the get/set endpoints exchange.
export type LogLevel = components["schemas"]["LogLevel"]["level"]

// Response shapes with no named schema component: the spec declares them inline, so
// they're pulled from the operation's response instead of a components["schemas"] key.
export type Me = operations["me"]["responses"]["200"]["content"]["application/json"]
export type SetupState = operations["getSetupStatus"]["responses"]["200"]["content"]["application/json"]
export type Health = operations["getHealthz"]["responses"]["200"]["content"]["application/json"]
export type IndexerStatus = operations["indexerStatus"]["responses"]["200"]["content"]["application/json"]
export type SearchParams = NonNullable<operations["searchIndexer"]["parameters"]["query"]>

export type Credentials = components["schemas"]["Credentials"]
export type OIDCConfig = components["schemas"]["OIDCConfig"]

// The keep-stored sentinel for secret settings (see openapi.yaml Setting) — a value,
// not a spec-mirrored type, so it stays hand-written.
export const REDACTED = "<redacted>"

// APIError carries the server's error envelope ({error, code}) plus the HTTP
// status, so callers branch on `code` (e.g. "invalid_credentials"), never on
// message text.
export class APIError extends Error {
  readonly status: number
  readonly code: string

  constructor(status: number, code: string, message: string) {
    super(message)
    this.name = "APIError"
    this.status = status
    this.code = code
  }
}

const MUTATING = new Set(["POST", "PUT", "PATCH", "DELETE"])

// AUTH_BOOTSTRAP endpoints handle their own 401 inline (session probe, login,
// setup, logout), so they are exempt from the 401 hard-redirect that every other
// endpoint triggers. A protected action (e.g. change-password) is NOT here — its
// 401 means the session expired and should redirect.
const AUTH_BOOTSTRAP = new Set(["/api/auth/me", "/api/auth/login", "/api/auth/setup", "/api/auth/logout"])

// readCsrfCookie returns the non-HttpOnly CSRF companion cookie the server
// sets at login (internal/web/api/csrf.go), or "" when absent.
function readCsrfCookie(): string {
  const match = document.cookie.match(/(?:^|;\s*)harbrr_csrf=([^;]*)/)
  return match ? decodeURIComponent(match[1]) : ""
}

type ErrorBody = { error?: string, code?: string }

// filenameFromContentDisposition pulls filename="..." out of an attachment
// Content-Disposition header, falling back to a dated default when the header
// is absent or unparseable.
function filenameFromContentDisposition(header: string | null): string {
  const match = header?.match(/filename="?([^"; ]+)"?/)
  return match?.[1] ?? `harbrr-backup-${new Date().toISOString().slice(0, 10)}.json`
}

// onAuthScreen reports whether the user is already on the login/setup screen,
// where a 401 hard-redirect would loop or be meaningless (bootstrap probes,
// failed logins).
function onAuthScreen(): boolean {
  return ["/login", "/setup"].includes(window.location.pathname.replace(getBaseUrl(), ""))
}

// toAPIError builds the thrown error for a non-ok response. Shared by unwrap and
// exportBackup (which needs the raw Response for its headers, not a JSON-unwrapped
// value). The 401 hard-redirect is the onResponse middleware's job, not this one's.
function toAPIError(response: Response, error: unknown): APIError {
  const body = (typeof error === "object" && error !== null ? error : undefined) as ErrorBody | undefined
  let code = "internal"
  let message = response.statusText
  if (body?.code) code = body.code
  if (body?.error) message = body.error
  return new APIError(response.status, code, message)
}

// unwrap turns an openapi-fetch {data, error, response} result into the resolved
// value or a thrown APIError. T is INFERRED from the typed client call's data
// shape — never pass it explicitly — so what a call site gets back is exactly
// what the generated types say the endpoint returns. The standard call shape is
// unwrap(api.http.<VERB>(path, args)).
export async function unwrap<T>(call: Promise<{ data?: T, error?: unknown, response: Response }>): Promise<T> {
  const { data, error, response } = await call
  if (!response.ok) throw toAPIError(response, error)
  return data as T
}

// ApiClient is the single choke point every management call goes through:
// base-path prefixing, CSRF header injection on mutations (onRequest middleware),
// the {error, code} envelope parsed into APIError, and the 401 hard-redirect to
// /login (onResponse middleware — skipped for auth endpoints and on the
// login/setup screens, so bootstrap probes and failed logins cannot loop).
// NEVER log request or response payloads here — settings bodies carry tracker
// credentials.
export class ApiClient {
  private csrfToken = ""

  // http is the typed openapi-fetch client. Call sites use it directly —
  // unwrap(api.http.<VERB>(path, args)) — the few methods below exist only
  // where a call needs more than that one-liner.
  readonly http: Client<paths>

  // fetchFn is the transport behind every request and the injection seam tests use
  // (see src/test/stubApi.ts): a stub here still runs the whole middleware pipeline,
  // so CSRF injection and the 401 redirect behave exactly as in production. It is a
  // replaceable field rather than a constructor-only capture because component tests
  // reach the module singleton through the hooks — stubApi swaps the singleton's
  // transport for the duration of a test and restores it after.
  fetchFn: (input: Request) => Promise<Response>

  // baseUrl is made absolute (origin + path prefix) because openapi-fetch constructs
  // a `Request` itself before dispatching — a plain browser `fetch("/api/...")` (the
  // old hand-rolled client's approach) resolves a relative URL against the document
  // implicitly, but `new Request("/api/...")` does not, so the origin is spelled out.
  // This is the same absolute URL the browser would have resolved either way.
  constructor(fetchFn?: (input: Request) => Promise<Response>) {
    this.fetchFn = fetchFn ?? ((input) => globalThis.fetch(input))
    this.http = createClient<paths>({
      baseUrl: `${window.location.origin}${getBaseUrl()}`,
      credentials: "same-origin",
      fetch: (input: Request) => this.fetchFn(input),
    })
    this.http.use({
      onRequest: ({ request }) => {
        if (MUTATING.has(request.method)) {
          const token = this.csrf()
          if (token !== "") request.headers.set("X-CSRF-Token", token)
        }
      },
      // schemaPath is the OpenAPI path including curly braces — the same spelling
      // as AUTH_BOOTSTRAP's entries.
      onResponse: ({ schemaPath, response }) => {
        if (response.status !== 401) return
        if (AUTH_BOOTSTRAP.has(schemaPath)) return
        if (onAuthScreen()) return
        this.onUnauthorized()
      },
    })
  }

  // onUnauthorized is replaceable for tests; the default is a full-page
  // navigation so all client state resets. It appends the current in-app location
  // as ?redirect= so an expired-session bounce returns the user where they were —
  // skipped on the auth screens themselves (which would loop / be meaningless).
  onUnauthorized: () => void = () => {
    const base = getBaseUrl()
    const target = `${base}/login`
    const path = window.location.pathname.slice(base.length) || "/"
    if (path === "/login" || path === "/setup") {
      window.location.assign(target)
      return
    }
    const redirect = path + window.location.search
    window.location.assign(`${target}?redirect=${encodeURIComponent(redirect)}`)
  }

  setCsrfToken(token: string | undefined) {
    this.csrfToken = token ?? ""
  }

  private csrf(): string {
    return readCsrfCookie() || this.csrfToken
  }

  // --- auth ---

  async getMe(): Promise<Me> {
    const me = await unwrap(this.http.GET("/api/auth/me"))
    this.setCsrfToken(me.csrfToken)
    return me
  }

  // getOIDCConfig probes the login screen's OIDC/SSO posture. The endpoint itself
  // always answers 200 (disabled default) even when OIDC isn't configured — the
  // catch here is a defensive fallback for the request failing outright (network,
  // server down), so the login screen still renders the password form.
  async getOIDCConfig(): Promise<OIDCConfig> {
    try {
      return await unwrap(this.http.GET("/api/auth/oidc/config"))
    } catch {
      return { enabled: false, authorizationUrl: "", disableBuiltInLogin: false, issuerUrl: "" }
    }
  }

  // --- backup export ---

  // exportBackup returns the encrypted bundle as a downloadable Blob rather than
  // going through unwrap: the response is offered as a file (Content-Disposition:
  // attachment), so the caller needs the raw bytes/filename, not a JSON-unwrapped
  // value. The bundle itself is still JSON (the {schemaVersion, payload} envelope),
  // so the parsed `data` is re-serialized into the Blob.
  async exportBackup(passphrase: string): Promise<{ blob: Blob, filename: string }> {
    const { data, error, response } = await this.http.POST("/api/export", { body: { passphrase } })
    if (!response.ok) throw toAPIError(response, error)
    const filename = filenameFromContentDisposition(response.headers.get("Content-Disposition"))
    return { blob: new Blob([JSON.stringify(data)], { type: "application/json" }), filename }
  }

  // --- enable/disable toggles (each picks the enable or disable path) ---

  setIndexerEnabled(slug: string, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/indexers/{slug}/enable", { params: { path: { slug } } }))
    return unwrap(this.http.POST("/api/indexers/{slug}/disable", { params: { path: { slug } } }))
  }

  setNotificationEnabled(id: number, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/notifications/{id}/enable", { params: { path: { id } } }))
    return unwrap(this.http.POST("/api/notifications/{id}/disable", { params: { path: { id } } }))
  }

  setDownloadClientEnabled(id: number, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/download-clients/{id}/enable", { params: { path: { id } } }))
    return unwrap(this.http.POST("/api/download-clients/{id}/disable", { params: { path: { id } } }))
  }

  setConnectionEnabled(id: number, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/app-connections/{id}/enable", { params: { path: { id } } }))
    return unwrap(this.http.POST("/api/app-connections/{id}/disable", { params: { path: { id } } }))
  }

  setAnnounceEnabled(id: number, enabled: boolean): Promise<void> {
    if (enabled) return unwrap(this.http.POST("/api/announce-connections/{id}/enable", { params: { path: { id } } }))
    return unwrap(this.http.POST("/api/announce-connections/{id}/disable", { params: { path: { id } } }))
  }
}

// createApi builds a fresh client — its own middleware stack and onUnauthorized —
// so tests do not leak into each other. Pass a fetch to inject a transport
// (src/test/stubApi.ts); omit it for the real network.
export function createApi(fetchFn?: (input: Request) => Promise<Response>): ApiClient {
  return new ApiClient(fetchFn)
}

export const api = createApi()
