import createClient from "openapi-fetch"
import { getBaseUrl } from "@/lib/base-url"
import type { components, operations, paths } from "@/types/api.gen"

// Convenience aliases onto the generated schema (web/src/types/api.gen.ts, committed,
// regenerated by `pnpm generate:api` from internal/web/swagger/openapi.yaml). These are
// derived references into the generated types, not hand-mirrored copies — never add a
// type here whose shape is retyped by hand instead of indexed from `components`/
// `operations`.
export type Instance = components["schemas"]["Instance"]
export type Setting = components["schemas"]["Setting"]
export type InstanceDetail = components["schemas"]["InstanceDetail"]
export type DefinitionSummary = components["schemas"]["DefinitionSummary"]
export type SettingField = components["schemas"]["SettingField"]
export type DefinitionDetail = components["schemas"]["DefinitionDetail"]
export type AddIndexer = components["schemas"]["AddIndexer"]
export type UpdateIndexer = components["schemas"]["UpdateIndexer"]
export type Capabilities = components["schemas"]["Capabilities"]
export type SearchResults = components["schemas"]["SearchResults"]
export type Release = components["schemas"]["Release"]
export type TestResult = components["schemas"]["TestResult"]
export type AppConnection = components["schemas"]["AppConnection"]
export type CreateConnection = components["schemas"]["CreateConnection"]
export type UpdateConnection = components["schemas"]["UpdateConnection"]
export type AnnounceConnection = components["schemas"]["AnnounceConnection"]
export type CreateAnnounceConnection = components["schemas"]["CreateAnnounceConnection"]
export type Notification = components["schemas"]["Notification"]
export type CreateNotification = components["schemas"]["CreateNotification"]
export type UpdateNotification = components["schemas"]["UpdateNotification"]
export type Proxy = components["schemas"]["Proxy"]
export type CreateProxy = components["schemas"]["CreateProxy"]
export type UpdateProxy = components["schemas"]["UpdateProxy"]
export type Solver = components["schemas"]["Solver"]
export type CreateSolver = components["schemas"]["CreateSolver"]
export type UpdateSolver = components["schemas"]["UpdateSolver"]
export type SyncProfile = components["schemas"]["SyncProfile"]
export type CreateSyncProfile = components["schemas"]["CreateSyncProfile"]
export type UpdateSyncProfile = components["schemas"]["UpdateSyncProfile"]
export type CrossSeedSnippet = components["schemas"]["CrossSeedSnippet"]
export type ConnectionIndexer = components["schemas"]["ConnectionIndexer"]
export type ConnectionStatus = components["schemas"]["ConnectionStatus"]
export type SyncResult = components["schemas"]["SyncResult"]
export type SyncReport = components["schemas"]["SyncReport"]
export type ConnectionSyncResult = components["schemas"]["ConnectionSyncResult"]
export type ApiKey = components["schemas"]["ApiKey"]
export type MintedApiKey = components["schemas"]["MintedApiKey"]
export type IndexerStats = components["schemas"]["IndexerStats"]
export type IndexerFailureCounts = components["schemas"]["IndexerStats"]["failures"]
export type CacheStats = components["schemas"]["CacheStats"]
export type CacheIndexerStats = components["schemas"]["CacheIndexerStats"]
export type CacheConfig = components["schemas"]["CacheConfig"]
export type CacheConfigUpdate = components["schemas"]["CacheConfigUpdate"]
export type ConnectionKind = components["schemas"]["AppConnection"]["kind"]
export type AnnounceKind = components["schemas"]["AnnounceConnection"]["kind"]
export type ProxyType = components["schemas"]["Proxy"]["type"]
// LogLevel is the bare string union call sites switch on; components["schemas"]["LogLevel"]
// is the {level: LogLevel} wrapper the get/set endpoints exchange.
export type LogLevel = components["schemas"]["LogLevel"]["level"]

// Response shapes with no named schema component: the spec declares them inline, so
// they're pulled from the operation's response instead of a components["schemas"] key.
export type Me = operations["me"]["responses"]["200"]["content"]["application/json"]
export type SetupState = operations["getSetupStatus"]["responses"]["200"]["content"]["application/json"]
export type Health = operations["getHealthz"]["responses"]["200"]["content"]["application/json"]
export type IndexerStatus = operations["indexerStatus"]["responses"]["200"]["content"]["application/json"]
export type SearchParams = NonNullable<operations["searchIndexer"]["parameters"]["query"]>

export type Credentials = components["schemas"]["Credentials"]

// The keep-stored sentinel for secret settings (see openapi.yaml Setting) — a value,
// not a spec-mirrored type, so it stays hand-written.
export const REDACTED = "<redacted>"

// APIError carries the server's error envelope ({error, code}) plus the HTTP
// status, so callers branch on `code` (e.g. "invalid_credentials"), never on
// message text.
export class APIError extends Error {
  readonly status: number
  readonly code: string

  constructor(status: number, code: string, message: string) {
    super(message)
    this.name = "APIError"
    this.status = status
    this.code = code
  }
}

const MUTATING = new Set(["POST", "PUT", "PATCH", "DELETE"])

// AUTH_BOOTSTRAP endpoints handle their own 401 inline (session probe, login,
// setup, logout), so they are exempt from the 401 hard-redirect that every other
// endpoint triggers. A protected action (e.g. change-password) is NOT here — its
// 401 means the session expired and should redirect.
const AUTH_BOOTSTRAP = new Set(["/api/auth/me", "/api/auth/login", "/api/auth/setup", "/api/auth/logout"])

// readCsrfCookie returns the non-HttpOnly CSRF companion cookie the server
// sets at login (internal/web/api/csrf.go), or "" when absent.
function readCsrfCookie(): string {
  const match = document.cookie.match(/(?:^|;\s*)harbrr_csrf=([^;]*)/)
  return match ? decodeURIComponent(match[1]) : ""
}

type ErrorBody = { error?: string, code?: string }

// ApiClient is the single choke point every management call goes through:
// base-path prefixing, CSRF header injection on mutations, the {error, code}
// envelope parsed into APIError, and the 401 hard-redirect to /login (skipped
// for auth endpoints and on the login/setup screens, so bootstrap probes and
// failed logins cannot loop). NEVER log request or response payloads here —
// settings bodies carry tracker credentials.
export class ApiClient {
  private csrfToken = ""

  // The fetch indirection (rather than passing globalThis.fetch directly) means the
  // client always dispatches through whatever `fetch` is current at call time, so
  // tests that stub the global after construction (vi.stubGlobal) still intercept it.
  // baseUrl is made absolute (origin + path prefix) because openapi-fetch constructs
  // a `Request` itself before dispatching — a plain browser `fetch("/api/...")` (the
  // old hand-rolled client's approach) resolves a relative URL against the document
  // implicitly, but `new Request("/api/...")` does not, so the origin is spelled out.
  // This is the same absolute URL the browser would have resolved either way.
  private readonly http = createClient<paths>({
    baseUrl: `${window.location.origin}${getBaseUrl()}`,
    credentials: "same-origin",
    fetch: (input: Request) => globalThis.fetch(input),
  })

  constructor() {
    this.http.use({
      onRequest: ({ request }) => {
        if (MUTATING.has(request.method)) {
          const token = this.csrf()
          if (token !== "") request.headers.set("X-CSRF-Token", token)
        }
      },
    })
  }

  // onUnauthorized is replaceable for tests; the default is a full-page
  // navigation so all client state resets. It appends the current in-app location
  // as ?redirect= so an expired-session bounce returns the user where they were —
  // skipped on the auth screens themselves (which would loop / be meaningless).
  onUnauthorized: () => void = () => {
    const base = getBaseUrl()
    const target = `${base}/login`
    const path = window.location.pathname.slice(base.length) || "/"
    if (path === "/login" || path === "/setup") {
      window.location.assign(target)
      return
    }
    const redirect = path + window.location.search
    window.location.assign(`${target}?redirect=${encodeURIComponent(redirect)}`)
  }

  setCsrfToken(token: string | undefined) {
    this.csrfToken = token ?? ""
  }

  private csrf(): string {
    return readCsrfCookie() || this.csrfToken
  }

  // unwrap turns an openapi-fetch {data, error, response} result into the resolved
  // value or a thrown APIError, applying the same 401 hard-redirect exemptions the
  // old hand-rolled request() used. T is INFERRED from the typed client call's data
  // shape — never pass it explicitly — so each method's declared return type is
  // checked against what the generated types say the endpoint actually returns.
  private async unwrap<T>(
    call: Promise<{ data?: T, error?: unknown, response: Response }>,
    endpoint: string
  ): Promise<T> {
    const { data, error, response } = await call
    if (!response.ok) {
      const body = (typeof error === "object" && error !== null ? error : undefined) as ErrorBody | undefined
      let code = "internal"
      let message = response.statusText
      if (body?.code) code = body.code
      if (body?.error) message = body.error
      const onAuthScreen = ["/login", "/setup"].includes(window.location.pathname.replace(getBaseUrl(), ""))
      if (response.status === 401 && !AUTH_BOOTSTRAP.has(endpoint) && !onAuthScreen) {
        this.onUnauthorized()
      }
      throw new APIError(response.status, code, message)
    }
    return data as T
  }

  // --- auth ---

  async getMe(): Promise<Me> {
    const me = await this.unwrap(this.http.GET("/api/auth/me"), "/api/auth/me")
    this.setCsrfToken(me.csrfToken)
    return me
  }

  getSetup(): Promise<SetupState> {
    return this.unwrap(this.http.GET("/api/auth/setup"), "/api/auth/setup")
  }

  setup(creds: Credentials): Promise<operations["postSetup"]["responses"]["201"]["content"]["application/json"]> {
    return this.unwrap(this.http.POST("/api/auth/setup", { body: creds }), "/api/auth/setup")
  }

  login(creds: Credentials): Promise<void> {
    return this.unwrap(this.http.POST("/api/auth/login", { body: creds }), "/api/auth/login")
  }

  logout(): Promise<void> {
    return this.unwrap(this.http.POST("/api/auth/logout"), "/api/auth/logout")
  }

  changePassword(currentPassword: string, newPassword: string): Promise<void> {
    return this.unwrap(
      this.http.POST("/api/auth/change-password", { body: { currentPassword, newPassword } }),
      "/api/auth/change-password"
    )
  }

  // --- definitions ---

  listDefinitions(): Promise<DefinitionSummary[]> {
    return this.unwrap(this.http.GET("/api/definitions"), "/api/definitions")
  }

  getDefinition(id: string): Promise<DefinitionDetail> {
    return this.unwrap(this.http.GET("/api/definitions/{id}", { params: { path: { id } } }), "/api/definitions/{id}")
  }

  // --- indexers ---

  listIndexers(): Promise<Instance[]> {
    return this.unwrap(this.http.GET("/api/indexers"), "/api/indexers")
  }

  addIndexer(body: AddIndexer): Promise<Instance> {
    return this.unwrap(this.http.POST("/api/indexers", { body }), "/api/indexers")
  }

  getIndexer(slug: string): Promise<InstanceDetail> {
    return this.unwrap(
      this.http.GET("/api/indexers/{slug}", { params: { path: { slug } } }),
      "/api/indexers/{slug}"
    )
  }

  // The server answers 204 (no body) on update, not the updated Instance — the old
  // hand-written type claimed `Promise<Instance>`, but no caller ever read the
  // resolved value (useUpdateIndexer invalidates and refetches instead), so this
  // return type is a pure accuracy fix, not a behavior change.
  updateIndexer(slug: string, body: UpdateIndexer): Promise<void> {
    return this.unwrap(
      this.http.PATCH("/api/indexers/{slug}", { params: { path: { slug } }, body }),
      "/api/indexers/{slug}"
    )
  }

  deleteIndexer(slug: string): Promise<void> {
    return this.unwrap(this.http.DELETE("/api/indexers/{slug}", { params: { path: { slug } } }), "/api/indexers/{slug}")
  }

  setIndexerEnabled(slug: string, enabled: boolean): Promise<void> {
    return enabled? this.unwrap(this.http.POST("/api/indexers/{slug}/enable", { params: { path: { slug } } }), "/api/indexers/{slug}/enable"): this.unwrap(this.http.POST("/api/indexers/{slug}/disable", { params: { path: { slug } } }), "/api/indexers/{slug}/disable")
  }

  testIndexer(slug: string): Promise<TestResult> {
    return this.unwrap(this.http.POST("/api/indexers/{slug}/test", { params: { path: { slug } } }), "/api/indexers/{slug}/test")
  }

  getIndexerStatus(slug: string): Promise<IndexerStatus> {
    return this.unwrap(this.http.GET("/api/indexers/{slug}/status", { params: { path: { slug } } }), "/api/indexers/{slug}/status")
  }

  getIndexerStats(slug: string): Promise<IndexerStats> {
    return this.unwrap(this.http.GET("/api/indexers/{slug}/stats", { params: { path: { slug } } }), "/api/indexers/{slug}/stats")
  }

  getIndexerCapabilities(slug: string): Promise<Capabilities> {
    return this.unwrap(
      this.http.GET("/api/indexers/{slug}/capabilities", { params: { path: { slug } } }),
      "/api/indexers/{slug}/capabilities"
    )
  }

  getCrossseedSnippet(slug: string): Promise<CrossSeedSnippet> {
    return this.unwrap(
      this.http.GET("/api/indexers/{slug}/crossseed-snippet", { params: { path: { slug } } }),
      "/api/indexers/{slug}/crossseed-snippet"
    )
  }

  // --- settings surfaces ---

  getHealth(): Promise<Health> {
    // /healthz lives beside /api, not under it.
    return this.unwrap(this.http.GET("/healthz"), "/healthz")
  }

  // getServerInfo reflects the live config.ServerConfig.Port, used to detect
  // app-sync connections whose stored harbrrUrl port has gone stale.
  getServerInfo(): Promise<components["schemas"]["ServerInfo"]> {
    return this.unwrap(this.http.GET("/api/server-info"), "/api/server-info")
  }

  listApiKeys(): Promise<ApiKey[]> {
    return this.unwrap(this.http.GET("/api/apikeys"), "/api/apikeys")
  }

  mintApiKey(name: string): Promise<MintedApiKey> {
    return this.unwrap(this.http.POST("/api/apikeys", { body: { name } }), "/api/apikeys")
  }

  revokeApiKey(id: number): Promise<void> {
    return this.unwrap(this.http.DELETE("/api/apikeys/{id}", { params: { path: { id } } }), "/api/apikeys/{id}")
  }

  listNotifications(): Promise<Notification[]> {
    return this.unwrap(this.http.GET("/api/notifications"), "/api/notifications")
  }

  createNotification(body: CreateNotification): Promise<Notification> {
    return this.unwrap(this.http.POST("/api/notifications", { body }), "/api/notifications")
  }

  // The server answers 204 on update; see the updateIndexer note (no caller reads
  // the resolved value — useUpdateNotification invalidates and refetches instead).
  updateNotification(id: number, body: UpdateNotification): Promise<void> {
    return this.unwrap(
      this.http.PATCH("/api/notifications/{id}", { params: { path: { id } }, body }),
      "/api/notifications/{id}"
    )
  }

  deleteNotification(id: number): Promise<void> {
    return this.unwrap(this.http.DELETE("/api/notifications/{id}", { params: { path: { id } } }), "/api/notifications/{id}")
  }

  setNotificationEnabled(id: number, enabled: boolean): Promise<void> {
    return enabled? this.unwrap(this.http.POST("/api/notifications/{id}/enable", { params: { path: { id } } }), "/api/notifications/{id}/enable"): this.unwrap(this.http.POST("/api/notifications/{id}/disable", { params: { path: { id } } }), "/api/notifications/{id}/disable")
  }

  testNotification(id: number): Promise<TestResult> {
    return this.unwrap(this.http.POST("/api/notifications/{id}/test", { params: { path: { id } } }), "/api/notifications/{id}/test")
  }

  // --- proxies ---

  listProxies(): Promise<Proxy[]> {
    return this.unwrap(this.http.GET("/api/proxies"), "/api/proxies")
  }

  createProxy(body: CreateProxy): Promise<Proxy> {
    return this.unwrap(this.http.POST("/api/proxies", { body }), "/api/proxies")
  }

  updateProxy(id: number, body: UpdateProxy): Promise<void> {
    return this.unwrap(this.http.PATCH("/api/proxies/{id}", { params: { path: { id } }, body }), "/api/proxies/{id}")
  }

  deleteProxy(id: number): Promise<void> {
    return this.unwrap(this.http.DELETE("/api/proxies/{id}", { params: { path: { id } } }), "/api/proxies/{id}")
  }

  // --- solvers ---

  listSolvers(): Promise<Solver[]> {
    return this.unwrap(this.http.GET("/api/solvers"), "/api/solvers")
  }

  createSolver(body: CreateSolver): Promise<Solver> {
    return this.unwrap(this.http.POST("/api/solvers", { body }), "/api/solvers")
  }

  updateSolver(id: number, body: UpdateSolver): Promise<void> {
    return this.unwrap(this.http.PATCH("/api/solvers/{id}", { params: { path: { id } }, body }), "/api/solvers/{id}")
  }

  deleteSolver(id: number): Promise<void> {
    return this.unwrap(this.http.DELETE("/api/solvers/{id}", { params: { path: { id } } }), "/api/solvers/{id}")
  }

  getCacheStats(): Promise<CacheStats> {
    return this.unwrap(this.http.GET("/api/cache/stats"), "/api/cache/stats")
  }

  flushCache(): Promise<components["schemas"]["CacheFlushResult"]> {
    return this.unwrap(this.http.POST("/api/cache/flush"), "/api/cache/flush")
  }

  getCacheConfig(): Promise<CacheConfig> {
    return this.unwrap(this.http.GET("/api/cache/config"), "/api/cache/config")
  }

  updateCacheConfig(body: CacheConfigUpdate): Promise<CacheConfig> {
    return this.unwrap(this.http.PUT("/api/cache/config", { body }), "/api/cache/config")
  }

  getLogLevel(): Promise<components["schemas"]["LogLevel"]> {
    return this.unwrap(this.http.GET("/api/config/log-level"), "/api/config/log-level")
  }

  setLogLevel(level: LogLevel): Promise<components["schemas"]["LogLevel"]> {
    return this.unwrap(this.http.PUT("/api/config/log-level", { body: { level } }), "/api/config/log-level")
  }

  listAllIndexerStats(): Promise<IndexerStats[]> {
    return this.unwrap(this.http.GET("/api/indexers/stats"), "/api/indexers/stats")
  }

  // --- app connections (sync targets) ---

  listConnections(): Promise<AppConnection[]> {
    return this.unwrap(this.http.GET("/api/app-connections"), "/api/app-connections")
  }

  createConnection(body: CreateConnection): Promise<AppConnection> {
    return this.unwrap(this.http.POST("/api/app-connections", { body }), "/api/app-connections")
  }

  getConnection(id: number): Promise<AppConnection> {
    return this.unwrap(this.http.GET("/api/app-connections/{id}", { params: { path: { id } } }), "/api/app-connections/{id}")
  }

  // The server answers 204 on update; see the updateIndexer note (no caller reads
  // the resolved value — useUpdateConnection invalidates and refetches instead).
  updateConnection(id: number, body: UpdateConnection): Promise<void> {
    return this.unwrap(
      this.http.PATCH("/api/app-connections/{id}", { params: { path: { id } }, body }),
      "/api/app-connections/{id}"
    )
  }

  deleteConnection(id: number): Promise<void> {
    return this.unwrap(this.http.DELETE("/api/app-connections/{id}", { params: { path: { id } } }), "/api/app-connections/{id}")
  }

  setConnectionEnabled(id: number, enabled: boolean): Promise<void> {
    return enabled? this.unwrap(this.http.POST("/api/app-connections/{id}/enable", { params: { path: { id } } }), "/api/app-connections/{id}/enable"): this.unwrap(this.http.POST("/api/app-connections/{id}/disable", { params: { path: { id } } }), "/api/app-connections/{id}/disable")
  }

  testConnection(id: number): Promise<TestResult> {
    return this.unwrap(this.http.POST("/api/app-connections/{id}/test", { params: { path: { id } } }), "/api/app-connections/{id}/test")
  }

  syncConnection(id: number): Promise<SyncReport> {
    return this.unwrap(this.http.POST("/api/app-connections/{id}/sync", { params: { path: { id } } }), "/api/app-connections/{id}/sync")
  }

  syncAllConnections(): Promise<ConnectionSyncResult[]> {
    return this.unwrap(this.http.POST("/api/app-connections/sync"), "/api/app-connections/sync")
  }

  getConnectionStatus(id: number): Promise<ConnectionStatus> {
    return this.unwrap(this.http.GET("/api/app-connections/{id}/status", { params: { path: { id } } }), "/api/app-connections/{id}/status")
  }

  setSelectedIndexers(id: number, instanceIds: number[]): Promise<void> {
    return this.unwrap(
      this.http.PUT("/api/app-connections/{id}/indexers", { params: { path: { id } }, body: { instanceIds } }),
      "/api/app-connections/{id}/indexers"
    )
  }

  // --- sync profiles (per-connection category/toggle overrides) ---

  listSyncProfiles(): Promise<SyncProfile[]> {
    return this.unwrap(this.http.GET("/api/sync-profiles"), "/api/sync-profiles")
  }

  createSyncProfile(body: CreateSyncProfile): Promise<SyncProfile> {
    return this.unwrap(this.http.POST("/api/sync-profiles", { body }), "/api/sync-profiles")
  }

  // The server answers 204 on update; see the updateIndexer note (no caller reads
  // the resolved value — useUpdateSyncProfile invalidates and refetches instead).
  updateSyncProfile(id: number, body: UpdateSyncProfile): Promise<void> {
    return this.unwrap(
      this.http.PATCH("/api/sync-profiles/{id}", { params: { path: { id } }, body }),
      "/api/sync-profiles/{id}"
    )
  }

  deleteSyncProfile(id: number): Promise<void> {
    return this.unwrap(this.http.DELETE("/api/sync-profiles/{id}", { params: { path: { id } } }), "/api/sync-profiles/{id}")
  }

  // --- announce connections (cross-seed push targets) ---

  listAnnounceConnections(): Promise<AnnounceConnection[]> {
    return this.unwrap(this.http.GET("/api/announce-connections"), "/api/announce-connections")
  }

  createAnnounceConnection(body: CreateAnnounceConnection): Promise<AnnounceConnection> {
    return this.unwrap(this.http.POST("/api/announce-connections", { body }), "/api/announce-connections")
  }

  deleteAnnounceConnection(id: number): Promise<void> {
    return this.unwrap(
      this.http.DELETE("/api/announce-connections/{id}", { params: { path: { id } } }),
      "/api/announce-connections/{id}"
    )
  }

  setAnnounceEnabled(id: number, enabled: boolean): Promise<void> {
    return enabled? this.unwrap(
      this.http.POST("/api/announce-connections/{id}/enable", { params: { path: { id } } }),
      "/api/announce-connections/{id}/enable"
    ): this.unwrap(
      this.http.POST("/api/announce-connections/{id}/disable", { params: { path: { id } } }),
      "/api/announce-connections/{id}/disable"
    )
  }

  // --- search ---

  searchIndexer(slug: string, params: SearchParams): Promise<SearchResults> {
    // Drop undefined/empty-string values so an unset filter is omitted from the
    // querystring entirely, matching the previous hand-rolled URLSearchParams pass.
    const query: SearchParams = {}
    for (const [key, value] of Object.entries(params) as [keyof SearchParams, unknown][]) {
      if (value !== undefined && value !== "") (query as Record<string, unknown>)[key] = value
    }
    return this.unwrap(
      this.http.GET("/api/indexers/{slug}/search", { params: { path: { slug }, query } }),
      "/api/indexers/{slug}/search"
    )
  }
}

export const api = new ApiClient()
