/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedIndexersRouteImport } from './routes/_authenticated/indexers'
import { Route as AuthenticatedDownloadClientsRouteImport } from './routes/_authenticated/download-clients'
import { Route as AuthenticatedCacheRouteImport } from './routes/_authenticated/cache'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndexersRoute = AuthenticatedIndexersRouteImport.update({
  id: '/indexers',
  path: '/indexers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDownloadClientsRoute =
  AuthenticatedDownloadClientsRouteImport.update({
    id: '/download-clients',
    path: '/download-clients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCacheRoute = AuthenticatedCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/cache': typeof AuthenticatedCacheRoute
  '/download-clients': typeof AuthenticatedDownloadClientsRoute
  '/indexers': typeof AuthenticatedIndexersRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/cache': typeof AuthenticatedCacheRoute
  '/download-clients': typeof AuthenticatedDownloadClientsRoute
  '/indexers': typeof AuthenticatedIndexersRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/cache': typeof AuthenticatedCacheRoute
  '/_authenticated/download-clients': typeof AuthenticatedDownloadClientsRoute
  '/_authenticated/indexers': typeof AuthenticatedIndexersRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/applications'
    | '/cache'
    | '/download-clients'
    | '/indexers'
    | '/resources'
    | '/search'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/applications'
    | '/cache'
    | '/download-clients'
    | '/indexers'
    | '/resources'
    | '/search'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/applications'
    | '/_authenticated/cache'
    | '/_authenticated/download-clients'
    | '/_authenticated/indexers'
    | '/_authenticated/resources'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indexers': {
      id: '/_authenticated/indexers'
      path: '/indexers'
      fullPath: '/indexers'
      preLoaderRoute: typeof AuthenticatedIndexersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/download-clients': {
      id: '/_authenticated/download-clients'
      path: '/download-clients'
      fullPath: '/download-clients'
      preLoaderRoute: typeof AuthenticatedDownloadClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cache': {
      id: '/_authenticated/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof AuthenticatedCacheRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedCacheRoute: typeof AuthenticatedCacheRoute
  AuthenticatedDownloadClientsRoute: typeof AuthenticatedDownloadClientsRoute
  AuthenticatedIndexersRoute: typeof AuthenticatedIndexersRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedCacheRoute: AuthenticatedCacheRoute,
  AuthenticatedDownloadClientsRoute: AuthenticatedDownloadClientsRoute,
  AuthenticatedIndexersRoute: AuthenticatedIndexersRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
